### ISSUE TITLE
Link goes off screen if the link is long enough

### ISSUE THREAD

**Issue by supraaxdd** [ItzBlinkzy/ShortKutt#1]
I've tried to shorten a link to test it out, and I grabbed a long link. It ended up going off the screen.  (Ref screenshot below)
![image](https://user-images.githubusercontent.com/54616428/212968755-b2ae566f-39e8-41b0-8ed8-bf2168c9752c.png)

**Comment by ItzBlinkzy** [comment]
Yes thanks for letting me know, I've forgotten to set a maximum width on the elements, just pushed an update (9788de0) that resolves this issue.
